name: Publish to NuGet

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: Build project ReportPortalNUnitLog4netClient
        run: dotnet build --configuration Release ReportPortalNUnitLog4netClient.csproj
      - name: Create the package for ReportPortalNUnitLog4netClient
        run: dotnet pack --configuration Release ReportPortalNUnitLog4netClient.csproj
      - name: Publish the package ReportPortalNUnitLog4netClient to NuGet
        run: dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }}